### ISSUE TITLE
Intermittently "no such file or directory" error seen when using trivy pre-commit hook

### ISSUE THREAD

**Issue by ocofaigh** [antonbabenko/pre-commit-terraform#691] opened 2024-07-15 15:54 UTC
### Describe the bug

We are running the trivy pre-commit hook like this:
```
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.0
  hooks:
    - id: terraform_trivy
      args:
        - --args=--skip-files="**/.terraform/**/*"
        - --args=--skip-files="**/examples/**/*.yaml"
        - --args=--skip-files="**/examples/**/*.yml"
        - --args=--skip-files="**/helm-charts/**/*"
        - --args=--skip-files="**/tests/**/*"
        - --args=--skip-files="common-dev-assets/**/*"
```

And we are intermittently seeing this:
```
Terraform validate with trivy.............................................Failed
- hook id: terraform_trivy
- exit code: 1

2024-07-10T16:47:27Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:27Z	INFO	Need to update the built-in policies
2024-07-10T16:47:27Z	INFO	Downloading the built-in policies...
2024-07-10T16:47:27Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:27Z	INFO	Need to update the built-in policies
2024-07-10T16:47:27Z	INFO	Downloading the built-in policies...
2024-07-10T16:47:27Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:27Z	INFO	Need to update the built-in policies
2024-07-10T16:47:27Z	INFO	Downloading the built-in policies...
2024-07-10T16:47:27Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:27Z	INFO	Need to update the built-in policies
2024-07-10T16:47:27Z	INFO	Downloading the built-in policies...
74.86 KiB / 74.86 KiB [-----------------------------------------------------------] [100](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/actions/runs/9878184694/job/27281554456#step:6:101).00% ? p/s 0s2024-07-10T16:47:27Z	FATAL	Fatal error	filesystem scan error: scan error: unable to initialize a scanner: unable to initialize a filesystem scanner: analyzer group error: post-analyzer init error: kubernetes scanner init error: mapfs file copy error: readdirent /github/home/.cache/trivy/policy/content/policies/cloud/policies/azure/database: no such file or directory
74.86 KiB / 74.86 KiB [-----------------------------------------------------------] 100.00% ? p/s 0s2024-07-10T16:47:27Z	ERROR	Falling back to embedded checks	err="check load error: manifest file open error (/github/home/.cache/trivy/policy/content/.manifest): open /github/home/.cache/trivy/policy/content/.manifest: no such file or directory"
74.86 KiB / 74.86 KiB [-----------------------------------------------------------] 100.00% ? p/s 0s74.86 KiB / 74.86 KiB [--------------------------------------------------------] 100.00% ? p/s 100ms2024-07-10T16:47:29Z	INFO	Detected config files	num=1
2024-07-10T16:47:29Z	INFO	Detected config files	num=1
2024-07-10T16:47:32Z	INFO	Detected config files	num=4
2024-07-10T16:47:33Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:33Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:33Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:34Z	INFO	Detected config files	num=1
2024-07-10T16:47:34Z	INFO	Detected config files	num=1
2024-07-10T16:47:34Z	INFO	Detected config files	num=1
2024-07-10T16:47:34Z	INFO	Misconfiguration scanning is enabled
2024-07-10T16:47:35Z	INFO	Detected config files	num=1
```

NOTE: It usually passes on retry

Reported to trivy here: https://github.com/aquasecurity/trivy/discussions/7145
But someone responded to say:

> I don't think this issue is related to Trivy. Most likely the way you are running your pre-commit hook or the environment it is running in is the cause of the error, which is making Trivy fallback to embedded policies.

so hence creating an issue here to see if its an issue with the hook itself

### How can we reproduce it?

pre-commit run --all-files

### Environment information

* OS:  

* `uname -a` and/or `systeminfo | Select-String "^OS"` output:

```bash
Linux a42b6fa0576a 6.6.14-0-virt #1-Alpine SMP Fri, 26 Jan 2024 11:08:07 +0000 x86_64 GNU/Linux
```

* Tools availability and versions:

```bash
trivy v0.53.0
```

* `.pre-commit-config.yaml`:

<details><summary>file content</summary>

```yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.92.0
  hooks:
    - id: terraform_trivy
      args:
        - --args=--skip-files="**/.terraform/**/*"
        - --args=--skip-files="**/examples/**/*.yaml"
        - --args=--skip-files="**/examples/**/*.yml"
        - --args=--skip-files="**/helm-charts/**/*"
        - --args=--skip-files="**/tests/**/*"
        - --args=--skip-files="common-dev-assets/**/*"
```

</details>

**Comment by yermulnik** [comment] 2024-07-15 17:09
I'm not very familiar with GH actions' internals, though might it be that the `/github/home/.cache/` being not writable is akin to trivy's issue?
https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/actions/runs/9878184694/job/27281554456#step:5:8
[Some people suggest](https://github.com/actions/setup-python/issues/816#issuecomment-2100504677) to run `sudo chown -R $(whoami) /github/home` (you may try and do this as part of [Set ownership step](https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager/actions/runs/9878184694/job/27281554456#step:4:1) or add a seperate step for that).

ps: I'm more of guesstimating 🤷🏻

**Comment by yermulnik** [comment] 2024-07-15 17:11
> I'm curious, is there any possibility to download policies separately and cache them, not on each run

I guess that should be doable with https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

**Comment by gamethis** [comment] 2024-07-16 01:12
you can avoid the random download by leveraging this command prior to trivy running
`trivy server --download-db-only`

**Comment by ocofaigh** [comment] 2024-07-16 10:19
@yermulnik If it was a permissions issue, it would happen every time. The issue is intermittent, and generally passes on retry. But thanks for the input. Going to try some of the other suggestions ..

**Comment by danielmapar** [comment] 2024-08-11 23:47
> ```yaml
> args:
>     - --hook-config=--parallelism-limit=1
> ```

This worked for me consistently.

**Comment by ocofaigh** [comment] 2024-08-12 14:25
Yes, we also had to use same workaround as described in https://github.com/antonbabenko/pre-commit-terraform/issues/691#issuecomment-2282929732

**Comment by yermulnik** [comment] 2024-08-12 15:23
I'm closing this issue since the resolution was confirmed.

**Closed by yermulnik** 2024-08-12 15:23 UTC
Labels: area/local_installation, bug_with_workaround, hook/terraform_trivy

**Comment by ocofaigh** [comment] 2024-08-13 10:35
FYI, further discussions are occurring here: https://github.com/aquasecurity/trivy/discussions/7145#discussioncomment-10316484
