### ISSUE TITLE
terraform_docs failing on TF0.12

### ISSUE THREAD

**Issue by thenom** [antonbabenko/pre-commit-terraform#52] opened 2019-06-19 11:37 UTC
Hi,

This is connected to https://github.com/antonbabenko/pre-commit-terraform/pull/45 that was fixed in v1.15.0.  That version has fixed the issue i had with mktemp but i am getting a new error on this version:

```
$ pre-commit run terraform_docs -a
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/19 10:45:22 At 62:1: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACE
```

But on another terraform config we have the error slightly differs:

```
$ pre-commit run terraform_docs -a
Trim Trailing Whitespace.................................................Passed
Fix End of Files.........................................................Passed
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/19 10:48:03 At 24:11: nested object expected: LBRACE got: ASSIGN
```

Both of these worked previously as they have fully populated README's.  I would look into this further but not sure where the files are that the error location refers too (if you point me in the right direction i am more than happy to investigate)

Thanks,

**Comment by antonbabenko** [comment] 2019-06-19 13:51
Please try v1.16.0.

If the problem persists please provide the failing snippet of the code you are trying to process.

**Comment by thenom** [comment] 2019-06-19 18:37
Ok, all autoupdated and still getting the same problems:
```
$ pre-commit run terraform_docs -a
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/19 19:27:28 At 62:1: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACE
```
and
```
pre-commit run terraform_docs -a
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/19 19:23:01 At 13:15: nested object expected: LBRACE got: ASSIGN
```

It is always 1 of the 2 above but as a test i created a new local tf repo with:
```
$ cat README.md
Test documentation

<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->

<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
$ cat variables.tf
variable "test_var" {
  description = "This is a test variable"
  default     = ""
  type        = string
}
$ cat .pre-commit-config.yaml
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.16.0
  hooks:
  - id: terraform_fmt
  - id: terraform_docs
```
and forced ran the pre-commit on it which worked:
```
$ pre-commit run -a
Terraform fmt............................................................Failed
hookid: terraform_fmt

Files were modified by this hook. Additional output:

variables.tf

Terraform docs...........................................................Failed
hookid: terraform_docs

Files were modified by this hook.
$ cat README.md
Test documentation

<!-- BEGINNING OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|:----:|:-----:|:-----:|
| test\_var | This is a test variable | string | `""` | no |

<!-- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->
```

I am afraid my TF modules are quite large and i am force running this to test it as i have not changed anything that would trigger it hence doing the minimal test.  I have tried it on 4 of our repos so far and all have failed with one of the 2 errors.

As a side test though i cleaned out all output in a few of the README's (between the block identifier hooks) and re-ran and still got the same error on each.

Just a note though, these are all v0.11 TF code that i am currently in the process of converting to 0.12, not sure if this is relevant but thought it might be worth mentioning as the test setup i ran was fine.

Thanks again

**Comment by thenom** [comment] 2019-06-20 16:09
Just an additional note, 1.16.0 works fine on pure TF 0.11 files.

**Comment by antonbabenko** [comment] 2019-06-24 19:08
I tried to reproduce this several times with Terraform 0.12 and latest pre-commit-terraform (v1.16.0), but can't reproduce it.

When Terraform 0.11 is used the `terraform_docs` hook uses previous behavior (no `awk` script of other magic is necessary) and it works fine.

Let's keep it open for some time in case someone experiences a similar issue as you are describing and can provide failing code.

**Comment by gstewart** [comment] 2019-06-25 00:16
Try with a single file (`variables.tf` for me) with something like this:

```
variable "test" {
  type        = "string"
  description = "testing"
}
```

With quotes around the string, you end up with two sets of quotes around it after the awk script runs `""string""`. This is what terraform docs seems to fail on. If you remove the quotes from around it, everything runs ok.

This only seems to happen when the type line comes first and then another line like description comes after. If the type line comes on the second line, or is the only line between the brackets, you'll get a different exception.

**Comment by thenom** [comment] 2019-06-25 09:27
Correct @gstewart,

I changed my test setup variables.tf to:
```
variable "test_var" {
  type        = "string"
  description = "This is a test variable"
  default     = ""
}
```

and now i get:
```
pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/25 10:12:16 At 3:15: nested object expected: LBRACE got: ASSIGN
```

If i take the quotes of the type it works fine.  I have removed all the quotes from my main terraform modules variable types and i still get this error:
```
pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/25 10:21:17 At 62:1: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACE
```

**Comment by antonbabenko** [comment] 2019-06-25 09:32
Yes, I could reproduce it.

@cytopia Once `type` is already enquoted it should not enquote it again.

**Comment by antonbabenko** [comment] 2019-06-25 12:37
Looks like it has been just fixed by @cytopia, so I have released [v1.17.0](https://github.com/antonbabenko/pre-commit-terraform/releases/v1.17.0).

**Closed** 2019-06-25 12:36 UTC

**Comment by thenom** [comment] 2019-06-25 15:49
I am afraid i am still get the same problem:
```
pre-commit autoupdate
Updating https://github.com/antonbabenko/pre-commit-terraform...[INFO] Initializing environment for https://github.com/antonbabenko/pre-commit-terraform.
updating v1.16.0 -> v1.17.0.
```
```
pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/25 16:35:45 At 62:1: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACE
```

**Comment by cytopia** [comment] 2019-06-25 15:59
@thenom 

I've tested it for the block you pasted above:
```
variable "test_var" {
  type        = "string"
  description = "This is a test variable"
  default     = ""
}
```

Maybe there is another exception which is causing it?

**Comment by thenom** [comment] 2019-06-25 18:06
@cytopia is there anyway i can get this to be more verbose to find out where it is having issues.  I cannot rules out this being my tf files but as terraform formats it and runs fine on it i can't see how.

**Comment by antonbabenko** [comment] 2019-06-26 08:45
Currently, there is no feature flag to turn on/off debugging, but you can make it easier to guess the failing line by combining all `*.tf` files into one and by removing everything except `variable` and `output` blocks.

Also, even if the code is not valid from `terraform_fmt` it should be good for `terraform_docs`, so you can run just it.

**Comment by cytopia** [comment] 2019-06-26 15:25
@thenom can you provide all variables and outputs you're using. Otherwise I won't be able to reproduce your error.

**Comment by thenom** [comment] 2019-06-26 16:00
Ok, i setup a new test folder and ran git init and copied the .pre-commit-yaml from my problematic terraform.

```
pre-commit run -a
Terraform fmt........................................(no files to check)Skipped
Terraform docs.......................................(no files to check)Skipped
```

Which was to be expected.  I then copied, one by one, each of my tf files over to this folder, ran `pre-commit run -a`, `git add *` and then `pre-commit run -a` again for every file copied.

```
$ cp ../terraform.module.elasticsearch/security-groups.tf ./
$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
$ git add *
$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
$ cp ../terraform.module.elasticsearch/variables.tf ./
$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
$ git add *
$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Passed
... and so on....
```

I didn't get a single problem...

I then reset this folder back to the initial git init and pre-commit-yaml.  I copied all the tf files in one, ran `pre-commit run -a`, `git add *` and then `pre-commit run -a` for the final time and it failed:
```
$ cp ../terraform.module.elasticsearch/* ./
$ pre-commit run -a
Terraform fmt........................................(no files to check)Skipped
Terraform docs.......................................(no files to check)Skipped
$ git add *
$ pre-commit run -a
Terraform fmt............................................................Passed
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/06/26 16:50:29 At 62:1: expected: IDENT | STRING | ASSIGN | LBRACE got: RBRACE
```

I then reset and tried it with 2 files in one go and it passed.

With this setup and my single variables.tf, i don't get a problem.  I also concated all outputs into a single file and that passed.....  The plot thickens....

**Comment by thenom** [comment] 2020-04-02 09:48
Just incase anyone lands here, after months of using SKIP=terraform_docs on my git commit. for this repo, i recently updated the pre-commit modules and terraform-docs it all now works fine.

```
$ brew upgrade terraform-docs
$ pre-commit autoupdate
```
(obviously on a mac but i am sure there will be other OS equivalents)

**Comment by antonbabenko** [comment] 2020-04-02 09:51
@thenom `pre-commit autoupdate` updated hooks to the very latest where `terraform_docs` has native support for Terraform 0.12.

Thanks for mentioning `SKIP=...`!

**Comment by puneeth072003** [comment] 2023-02-05 09:51
Hey guys I'm still getting the issue
```
$  pre-commit run terraform_docs -a
Terraform docs...........................................................Failed
- hook id: terraform_docs
- exit code: 1
```
May i know how to fix that?

**Comment by MaxymVlasov** [comment] 2023-02-06 13:40
`git add -A` to add fixes to your git staged changes.
