### ISSUE TITLE
Checkov hard fail question

### ISSUE THREAD

**Issue by mtweeman** [antonbabenko/pre-commit-terraform#709] opened 2024-08-31 15:05 UTC
Hey,

I noticed that normally, during Checkov execution on my machine, I was not able to filter results using `--hard-fail-on MEDIUM` due to missing API key. I see that it's possible with pre-commit hook. How were you able to setup hook for Checkov, so it doesn't need API key?  Am I missing something?

**Comment by MaxymVlasov** [comment] 2024-09-02 12:55
Or use Prisma API key, or don't filter them
Duplicate of https://github.com/antonbabenko/pre-commit-terraform/issues/568

Checkov team doesn't plan to provide such functionality w/o API key - https://github.com/bridgecrewio/checkov/issues/5560#issuecomment-1722313286

**Closed by MaxymVlasov** 2024-09-02 12:55 UTC

**Comment by MaxymVlasov** [comment] 2024-09-02 12:57
Or you can write your own filter solution and submit PR :)
